<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98010a0b68656c6c6f2e70726f746f120570726f746f221c0a0c48656c" .
            "6c6f52657175657374120c0a046e616d65180120012809221d0a0a48656c" .
            "6c6f5265706c79120f0a076d657373616765180120012809323d0a054865" .
            "6c6c6f12340a0853617948656c6c6f12132e70726f746f2e48656c6c6f52" .
            "6571756573741a112e70726f746f2e48656c6c6f5265706c792200620670" .
            "726f746f33"
        ));
        static::$is_initialized = true;
    }
}

